name: Deploy UrbanCart 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
  # The job will run on latest ubuntu runner 
    runs-on: ubuntu-latest

    steps:
      # Checkouts the code from main branch of the repo and places it in ubuntu runner
      - name: Checkout main branch code
        uses: actions/checkout@v4

      # Buildx is Docker's advanced builder. Which allows multi-stage builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub with the credentials stored in GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and Push Docker Image to Docker Hub
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
        #context is the path where Dockerfile is located and if push is true then it pushes the image to Docker Hub
          context: .
          file: ./Dockerfile
          push: true
          tags: pradeep313/urbancart:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
      # Trigger Render Deployment using renders deploy hook stored in GitHub Secrets
      - name: Trigger Render Deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
